# Generated by Django 2.0.1 on 2018-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='详细'),
        ),
    ]
