# Generated by Django 2.0.1 on 2018-04-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_icon_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='star',
        ),
    ]
