# Generated by Django 2.0.1 on 2018-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_course_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='star',
            field=models.IntegerField(default=5, verbose_name='星级'),
        ),
    ]
