# Generated by Django 2.0.1 on 2018-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180418_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='star',
            field=models.CharField(max_length=50, verbose_name='星级'),
        ),
    ]
